name: Eleventy Build
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
        with:
          ref: main
      - uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}